version: "3.9"
services:
  app-static:
    container_name: portfolio-teste
    image: node:20
    working_dir: /app
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
    restart: unless-stopped
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
